//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrafficEventEntity
    {
        public System.Guid ID { get; set; }
        public string ProgramCode { get; set; }
        public string ChannelName { get; set; }
        public string ProgramTitle1 { get; set; }
        public string ProgramTitle2 { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    
        public virtual ChannelEntity Channel { get; set; }
    }
}
